apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  type: LoadBalancer
  ports: #The list of ports that are exposed by this service
    - protocol: TCP #Default is TCP
      port: 9376 #The port that will be exposed by this service.
      targetPort: 8080 #Number or name of the port to access on the pods targeted by the service.